### ISSUE TITLE
Create entity from adblu level attribute

### ISSUE THREAD

**Issue by Powerdata44** [msp1974/homeassistant-jlrincontrol#105]
Hi all,

Please can someone give me code advice of how to get sensor information from my land-rover.

Am create new guide lovelace card of Adblu's currently level on my home assistant. 

 example of code please... I found sensors list in All-info attribute but where to start in code for just one from attribute. 

Am ongoing learning using coding.

Many thanks

**Comment by ismarslomic** [comment]
You can find examples in https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/Recipes.md

**Comment by Powerdata44** [comment]
Sorry that's doesn't explaining what I am looking for... am looking for one reading from attribute which is Adblu not any others.

**Comment by ismarslomic** [comment]
You asked: "example of code please... I found sensors list in All-info attribute but where to start in code for just one from attribute."

and you can find an example on how to extract an specific attribute from All info to separate sensor, in provided link.

**Comment by Powerdata44** [comment]
As I mentioned that I am learning using code. I am trying toe create gauge level of Adblu level... (realised I mistyped "guide" I mean gauge lovelace box.

**Comment by ismarslomic** [comment]
Okey, I didnt catch that. Then your question is about visualization in HA, and not directly related to JLR integration.

Please see official HA documentation for [Gauge Card](https://www.home-assistant.io/dashboards/gauge/). For further HA questions, please reach out to the HA forum

**Comment by Powerdata44** [comment]
![Screenshot_20231223_205316_Home Assistant](https://github.com/msp1974/homeassistant-jlrincontrol/assets/7041246/34b4408b-d0db-46c2-af55-25d676f4475f)
What I try to explain is.. pik one in list of all-info.... I want use reading (see arrow) in my screenshot- use that in gauge.. where code to collect these specific attribute?

**Comment by msp1974** [comment]
The link that @ismarslomic pointed you to does explain this if you read down.  Example below from that link

```
template:
  - sensor:
      - name: "My Car Battery Sensor"
        icon: "mdi:car-battery"
        state: "{{ state_attr('sensor.my_car_all_info','core status').batteryVoltage }}"
        attributes:
          battery_status: "{{ state_attr('sensor.my_car_all_info','core status').batteryStatus }}"
          tu_status: "{{ state_attr('sensor.my_car_all_info','core status').tuStatusPower }}"
          tu_serial: "{{ state_attr('sensor.my_car_all_info','attributes').telematicsDevice.serialNumber }}"
```
